import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CartProvider } from "../app/context/CartContext";
import { Ubuntu } from "next/font/google";
import SessionWrapper from './components/SessionWrapper'


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const ubuntu = Ubuntu({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <SessionWrapper>
        <CartProvider> 
          {children}
        </CartProvider>
      </SessionWrapper>
       
      </body>
    </html>
  );
}
